---
- hosts: linux
  become: yes
  tasks:
   - name: Update apt cache and install Nginx
     apt:
       name: nginx
       state: latest
       update_cache: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx

- hosts: windows
  become_method: runas
  tasks:
  - name: Create a new file
    win_file:
      path: C:\output.pdf
      state: touch

  - name: Create a new folder
    win_file:
      path: C:\ansible_examples\
      state: directory

  - name: Copy File
    win_copy:
      src: C:\output.pdf
      dest: C:\ansible_examples\
      remote_src: yes

  - name: Modifying a registry, adding name and data
    win_regedit:
      path: HKLM:\SOFTWARE\MattSoft
      name: Matt
      data: SHHHH
      state: present

  - name: Change power plan to high performance
    win_power_plan:
      name: high performance
