---
- hosts: linux
  become: yes
  vars:
    server_name: localhost
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


- hosts: windows
  become_method: runas
  tasks:
  - name: Create a new file
    win_file:
      path: C:\output.pdf
      state: file

  - name: Create a new folder
    win_file:
      path: C:\ansible_examples\
      state: directory

  - name: Copy File
    win_copy:
      src: C:\output.pdf
      dest: C:\ansible_examples\
      remote_src: yes

  - name: Modifying a registry, adding name and data
    win_regedit:
      path: HKLM:\SOFTWARE\MattSoft
      name: Matt
      data: SHHHH
      state: present

  - name: Change power plan to high performance
    win_power_plan:
      name: high performance